### ISSUE TITLE
Building Project On Local Machine

### ISSUE THREAD

**Issue by umitkose** [bakdata/dedupe#5]
Hello I have tried to import project to latest eclipse version bu I could not succeed. Can you share which IDE you use for development so I can try it.

**Comment by AHeise** [comment]
Hi @umitkose , 

sorry for the late reply. We use IntelliJ. 

Before importing into Eclipse, make sure you have the [lombok](https://projectlombok.org/setup/eclipse) plugin and a recent JDK installed.

Can you try to run
```
./gradlew clean build
```
locally? That should show if building works at all. We have tested on Windows and Mac so far (+Linux from Travis).

If you experience further issues, can you provide some exemplary errors?

Btw if you just want to use the library, you could use the Maven Central release https://mvnrepository.com/artifact/com.bakdata.dedupe/common/1.0.0

**Comment by AHeise** [comment]
I'm closing the ticket for now.

If you have further questions, I could reopen it.
